export const COUNTRIES_MAPPER = {
  de: "Niemcy",
  "gb-sct": "Szkocja",
  hu: "Węgry",
  ch: "Szwajcaria",
  es: "Hiszpania",
  hr: "Chorwacja",
  it: "Włochy",
  al: "Albania",
  si: "Słowenia",
  dk: "Dania",
  rs: "Serbia",
  "gb-eng": "Anglia",
  pl: "Polska",
  nl: "Holandia",
  at: "Austria",
  fr: "Francja",
  be: "Belgia",
  sk: "Słowacja",
  ro: "Rumunia",
  ua: "Ukraina",
  tr: "Turcja",
  ge: "Gruzja",
  pt: "Portugalia",
  cz: "Czechy",
};
